title = 'But I Digress'
baseURL = 'https://but-i-digress.ca/'
languageCode = 'en-ca'
theme = 'Mainroad'
contentDir = 'content'

[service.disqus]
shortname = ""

[services.googleAnalytics]
ID = ""

#[Author]
#name = "Michael Soulier"
#bio = "Oh sure, *now* you ask about me"
#avatar = ""

[Params]
description = "Randon neuron firings, heedless of the repurcussions" # Site description. Used in meta description
copyright = "Michael Soulier" # Footer copyright holder, otherwise will use site title
opengraph = false # Enable OpenGraph if true
schema = false # Enable Schema
twitter_cards = false # Enable Twitter Cards if true
readmore = false # Show "Read more" button in list if true
authorbox = false # Show authorbox at bottom of pages if true
toc = true # Enable Table of Contents
pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
mainSections = ["pages", "posts"] # Specify section pages to show on home page and the "Recent articles" widget
dateformat = "2006-01-02" # Change the format of dates
mathjax = false # Enable MathJax
mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
#  customCSS = ["css/custom.css"] # Include custom CSS files
#  customJS = ["js/custom.js"] # Include custom JS files

[Params.style.vars]
highlightColor = "#e22d30" # Override highlight color

# Override font-family sets
# Take care of different quotes OR escaping symbols in these params if necessary
fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
# Secondary font-family set responsible for pre, code, kbd, and samp tags font
fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
#image = "img/placeholder.png" # Logo image. Path relative to "static"
#title = "Mainroad" # Logo title, otherwise will use site title
#subtitle = "Just another site" # Logo subtitle

[Params.thumbnail]
visibility = ["list", "posts"] # Control thumbnail visibility

[Params.sidebar]
home = "right" # Configure layout for home page
list = "left"  # Configure layout for list pages
single = false # Configure layout for single pages
# Enable widgets in given order
widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
recent_num = 5 # Set the number of articles in the "Recent articles" widget
categories_counter = false # Enable counter for each category in "Categories" widget
tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
cached = false # activate cache if true
# Enable parts of social widget
#facebook = "msoulier"
twitter = "msoulier"
mastodon = "msoulier"
#instagram = "msoulier"
linkedin = "msoulier"
#telegram = "msoulier"
github = "msoulier"
#gitlab = "msoulier"
#bitbucket = "msoulier"
email = "msoulier@digitaltorque.ca"

# Custom social links
#[[Params.widgets.social.custom]]
#title = "Youtube"
#url = "https://youtube.com/user/username"
#icon = "youtube.svg" # Optional. Path relative to "layouts/partials"
#rel = "noopener noreferrer" # Set to false to remove the rel attribute

#[[Params.widgets.social.custom]]
#title = "My Home Page"
#url = "https://example.com"

[Params.widgets.search]
cached = false # activate cache if true
url = "https://google.com/search"
[Params.widgets.search.input]
name = "sitesearch"
pre = ""
